import Head from 'next/head'
import {FormEvent, useEffect, useState} from "react";
import Searchbar from "@/components/searchbar";
import {Hero} from "@/common/hero.types";
import Link from "next/link";
import Image from "next/image";


export default function Home() {
    const [results, setResults] = useState<Hero[]>([]);
    return (
        <>
            <Head>
                <title>My SuperHero</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Searchbar searchResult={setResults} />
                <ul>
                    {results.map(hero => {
                        return <li key={hero.id}>
                            <Link href={`/profile/${hero.id}`} target="_blank">
                                <Image src={hero.image.url} alt={hero.name} width="120" height="150"></Image>
                                <span>{hero.name}</span>
                            </Link>
                        </li>
                    })}
                </ul>
                <p>{results.length === 0 && "No Results Found!"}</p>
            </main>
        </>
    )
}
